### ISSUE TITLE
Port all Halogen examples to HalogenHooks

### ISSUE THREAD

**Issue by milesfrain** [JordanMartinez/purescript-cookbook#138]
- [ ] AceHalogenHooks #120
- [x] BasicHalogenHooks                                                                                  
- [x] ComponentsHalogenHooks                                                                             
- [x] ComponentsInputsHalogenHooks                                                                       
- [x] ComponentsMultitypeHalogenHooks                                                                    
- [x] DriverIoHalogenHooks                                                                               
- [x] DriverRoutingHalogenHooks                                                                          
- [x] DriverWebsocketsHalogenHooks                                                                       
- [ ] EffectsAffAjaxHalogenHooks                                                                         
- [ ] EffectsEffectRandomHalogenHooks                                                                    
- [ ] HigherOrderComponentsHalogenHooks                                                                  
- [x] InterpretHalogenHooks                                                                              
- [x] KeyboardInputHalogenHooks                                                                          
- [x] LifecycleHalogenHooks

https://github.com/purescript-halogen/purescript-halogen/tree/master/examples

**Comment by JordanMartinez** [comment]
I'm claiming this one next.

**Comment by JordanMartinez** [comment]
`ace` isn't in the package set :-/

**Comment by JordanMartinez** [comment]
I'm not sure whether the following recipes should be implemented based on their readme's content. Thoughts?
- `effects-aff-ajax`: "demonstrates how to make an AJAX request in a component `eval` function." Isn't this already shown via `ImagePreviewsHalogenHooks`?
- `effects-effect-random`: "demonstrates how to use an `Effect` function in a component `eval` function." Isn't this already shown in various recipes here already? The example they use is generating a random number. We've already got recipes for doing that...
- `higher-order-components`: "illustrates how to define and use a higher-order component". Hooks kind of make higher-order components pointless now because one can just define a hook (e.g. halogen-select) that can be embedded into another hook that is used to create a component

**Comment by JordanMartinez** [comment]
Aside from the above comment and #120, this issue is basically done.

**Comment by milesfrain** [comment]
> I'm not sure whether the following recipes should be implemented based on their readme's content. Thoughts?

Yes, that definitely looks like duplication.
It would be good to note this for readers attempting to find equivalent recipes to the examples. Not sure where to put this note. Maybe add something like this to the [examples readme](https://github.com/thomashoneyman/purescript-halogen-hooks/blob/master/examples/README.md):
> Hooks versions of the classic Halogen [examples](https://github.com/purescript-halogen/purescript-halogen/tree/master/examples) can be found in the [PureScript Cookbook](https://github.com/JordanMartinez/purescript-cookbook/issues/138). Note that the following recipes were skipped due to redundancy: (add your summary of skipped recipes)
