### ISSUE TITLE
add some CSS styling for the web recipes?

### ISSUE THREAD

**Issue by afcondon** [JordanMartinez/purescript-cookbook#191]
any interest in this? just thinking of something like some `margin: auto` to make the various web recipes center in the window...i did a search for "css" in issues and didn't see anything but maybe you have reasons for keeping it spartan for now?

**Comment by milesfrain** [comment]
One of the next steps for web recipes is autogenerating ([try](https://try.purescript.org/?gist=b08c95c9304a282e6872b882a81ccb25)) links next to every web checkmark in the table.
So I don't think centering will be too necessary with the output in the side-pane.

I'm working on a collect of TPS updates, and one of them will allow launching the above link from:
```
https://try.purescript.org/?file=https://raw.githubusercontent.com/JordanMartinez/purescript-cookbook/master/recipes/CatGifsHalogenHooks/src/Main.purs
```
rather than a gist.

**Comment by afcondon** [comment]
>One of the next steps for web recipes is autogenerating ([try](https://try.purescript.org/?gist=b08c95c9304a282e6872b882a81ccb25)) links next to every web checkmark in the table. ...

@milesfrain sounds like a good plan. I’ll close this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
