### ISSUE TITLE
Recipes with dependencies beyond spago

### ISSUE THREAD

**Issue by Kamirus** [JordanMartinez/purescript-cookbook#56]
Hi, many thanks for creating such a project!

We thought about adding some recipes about [purescript-selda](https://github.com/Kamirus/purescript-selda), but it would require more dependencies like npm dependencies and (ideally) PostgreSQL.

Is it a place for such recipes? Do you plan to support it?

**Comment by JordanMartinez** [comment]
The `npm` dependencies shouldn't be an issue. However, were you thinking of setting up an entire database in this repo? If so, that could get tricky...

**Comment by JordanMartinez** [comment]
Regarding `npm` dependencies, there are two ways we could do this:
1. Stores all dependencies in the repo's `package.json` file. This is the easiest to do because all other code should remain the same. However, it doesn't help others know which `npm` dependencies are installed for a given recipe. Moreover, if one recipe should rely on version A and another rely on version B of the same package, it will cause problems.
2. Store a recipe's dependencies in the recipe folder. This is better for the end-user but makes maintenance a bit harder to do. If someone `require`s a dependency in their FFI, will it resolve to the correct module?

**Comment by JordanMartinez** [comment]
@milesfrain I think this is the last issue that needs to be figured out. Once done, we could clean things up one more time and then I think this repo will be ready for recipe requests. While #63 might be a problem, I'm less worried about it.

**Comment by milesfrain** [comment]
My plan is to cross this bridge when incorporating a recipe that requires these npm dependencies. We could give that a shot now with some `affjax` + `xhr2` recipes.

**Comment by JordanMartinez** [comment]
I've tried to add a recipe for [`purescript-bigints`](https://pursuit.purescript.org/packages/purescript-bigints/) and have encountered a number of issues.

Here's the outcomes I'm trying to reach
1. each recipe folder has its own `package.json` if it needs to install npm dependencies. This tells users which npm dependencies and versions are being used in that recipe. This also makes it easier for maintainers to remove the recipe without breaking other things.
1. each recipe reuses the `.spago` and `output` folders, so that we only compile `purescript-either` once if 2+ recipes depend on it (either directly or transitively).
1. the root directory's `package.json` file only contains the `devDependencies` for `purescript`, `spago`, and `parcel`. In other words, we don't want this file getting polluted with countless other `npm` dependencies, particularly in cases where one recipe might depend on version A whereas another depends on version B.
1. the root folder's `node_modules` folder stores all `npm` dependencies across all recipes. Otherwise, `require`s in the `output` folder don't seem to work.

The first three are relatively straightforward to do, but also supporting the 3rd one is difficult. As far as I know, `npm` doesn't allow you to specify where the `package.json` file is located. So you can't do something like `npm --config recipes/BigInts/package.json install`. Thus, I read over a [comparison between `npm`, `yarn`, and `pnpm`](https://rushjs.io/pages/maintainer/package_managers/).

[`pnpm`](https://pnpm.js.org/en/) seemed promising, not only because it [solves the doppelganger problem](https://rushjs.io/pages/advanced/npm_doppelgangers/) (which will improve our CI build times when we have numerous recipes with FFI to `npm` dependencies), but because it [supports multi-package monorepos via "workspaces"](https://pnpm.js.org/en/workspaces).

After playing with it (I'll submit what I have so far as a PR), I found that I could run `make BigInts-node` and it would resolve the FFI to the `big-integer` npm dependency just fine. However, when I ran `make BigInts-web`, I noticed that it would always add `big-integer` to the root folder's `package.json` file, thereby missing the 3rd outcome above.

**Comment by JordanMartinez** [comment]
@Kamirus I'm going to close this issue and open two other issues. One will be for npm dependencies (which is what the gist of this issue is) since it is the more pressing matter, and the second will be for non-npm dependencies (e.g. `postgresql`) which is a less pressing matter.
