### ISSUE TITLE
Spago "Getting started" recipes

### ISSUE THREAD

**Issue by f-f** [JordanMartinez/purescript-cookbook#71]
In the Spago docs we have [recipes to get started with other tooling (i.e. Parcel/Webpack/Nodemon)](https://github.com/purescript/spago#make-a-project-with-purescript--javascript)

I think they might be better suited here, so that e.g. they can be tested in CI and kept working over time, plus it would be a nice way to have people discover the Cookbook (i.e. #7).

Would this be a welcome addition?

**Comment by milesfrain** [comment]
The cookbook currently only uses `parcel`, although I don't think this is a great resource for demonstrating how to setup a `parcel` project. The bundling steps occur in the `makefile`, which is designed to minimize code duplication, but comes at the cost of additional complexity when trying to reason about what's happening for a given recipe.

So I think demonstrating different workflows and bundlers should be handled in a separate "templates" directory or project.

But don't know if there's much to gain with showing _all_ bundler possibilities. Opinionated guidance on the bundler that we feel offers the smoothest beginner experience might be the better strategy. Folks who _need_  to use another bundler (like `webpack`) are presumably familiar with that bundler and should hopefully be able to translate our simpler bundling examples.

**Comment by JordanMartinez** [comment]
> So I think demonstrating different workflows and bundlers should be handled in a separate "templates" directory or project.

I agree with @milesfrain here. To make it easier to run backend-specific implementations of recipes with a consistent user-friendly command, we're currently using `make`. While `make` is ideal for our use case, it wouldn't be ideal for what you have in mind. By standardizing all web recipes to use `parcel`, it reduces our maintenance burden.

This is a cookbook for PureScript, not necessarily bundler strategies. While we could add a separate `bundler-strategies` folder for this very purpose, I think it would be stepping outside the scope of this project. 
Granted, I do think those strategies should be documented, but just not here. It would make more sense to create a `spago-cookbook` repo, `purescript-bundle-strategies` repo, or something.

> plus it would be a nice way to have people discover the Cookbook (i.e. #7).

To clarify that issue further, I meant for the following resources to link to it:
- PS website
- PS docs repo
- PS book
- my learning repo
- Thomas' real world halogen guide

The above resources are usually what new people find first when discovering PureScript. I imagine that they would be a better place for such a link rather than `spago`.

**Comment by JordanMartinez** [comment]
@f-f I'm going to close this issue. I think your 'Getting Started with Spago' recipes would be better if they went into a separate cookbook. You might want to start with our repo as a way to jumpstart that effort.
